name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - pip

  # Conda packages (compiled libraries)
  - blas
  - bzip2
  - ca-certificates
  - libffi
  - libzlib
  - ncurses
  - openssl
  - python-dateutil
  - readline
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - mkl
  - numpy
  - pandas
  - sqlalchemy

  # Pip packages (pure Python)
  - pip:
      - annotated-doc
      - annotated-types
      - anyio
      - asttokens
      - bottleneck
      - click
      - colorama
      - comm
      - coverage
      - debugpy
      - decorator
      - dnspython
      - email-validator
      - exceptiongroup
      - executing
      - fastapi
      - fastapi-cli
      - fastapi-core
      - greenlet
      - h11
      - h2
      - hpack
      - httpcore
      - httptools
      - httpx
      - hyperframe
      - idna
      - importlib-metadata
      - iniconfig
      - ipykernel
      - ipython
      - ipython_pygments_lexers
      - jedi
      - jinja2
      - jupyter_client
      - jupyter_core
      - markdown-it-py
      - markupsafe
      - matplotlib-inline
      - mdurl
      - nest-asyncio
      - numexpr
      - parso
      - platformdirs
      - pluggy
      - prompt-toolkit
      - psutil
      - pure_eval
      - pydantic
      - pydantic-core
      - pygments
      - pyodbc
      - pytest
      - pytest-cov
      - python-dotenv
      - python-multipart
      - pytz
      - pywin32
      - pyyaml
      - pyzmq
      - rich
      - rich-toolkit
      - shellingham
      - six
      - sniffio
      - stack_data
      - starlette
      - tbb
      - tbb-devel
      - tornado
      - traitlets
      - typer
      - typer-slim
      - typer-slim-standard
      - typing-extensions
      - typing-inspection
      - uvicorn
      - uvicorn-standard
      - watchfiles
      - wcwidth
      - websockets
      - zipp
