name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          use-mamba: true

      # 3. Create Conda environment from environment.yml
      - name: Create Conda environment
        run: conda env create -f environment.yml

      # 4. Run basic tests
      - name: Run tests
        run: conda run -n myenv pytest -q

      # 5. Run tests with coverage
      - name: Run tests with coverage
        run: |
          conda run -n myenv pytest -q \
            --cov=. \
            --cov-report=term \
            --cov-report=xml \
            --cov-report=html

      # 6. Prepare coverage artifacts for Pages
      - name: Prepare coverage artifacts
        run: |
          mkdir -p sites
          mv htmlcov sites/
          mv coverage.xml sites/

      # 7. Upload the artifacts
      - name: Upload the artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./sites

  Deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy the artifacts
        uses: actions/deploy-pages@v4
